### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by rainwoodman** [nasa-lambda/cmb_footprint#1]
Hi,

I tried to run the plot_lss script from a clean checkout:

```
python plot_lss.py
```

the stack trace is here:

```
python plot_lss.py
Traceback (most recent call last):
  File "plot_lss.py", line 15, in <module>
    from cmb_footprint import footprint
  File "/home/yfeng1/source/cmb_footprint/footprint.py", line 24, in <module>
    from cmb_footprint.config_handler import ConfigHandler
  File "/home/yfeng1/source/cmb_footprint/config_handler.py", line 28, in <module>
    from astropy.coordinates import SkyCoord
  File "/home/yfeng1/.local/lib/python2.7/site-packages/astropy/coordinates/__init__.py", line 13, in <module>
    from .baseframe import *
  File "/home/yfeng1/.local/lib/python2.7/site-packages/astropy/coordinates/baseframe.py", line 1218, in <module>
    from .earth import EarthLocation
  File "/home/yfeng1/.local/lib/python2.7/site-packages/astropy/coordinates/earth.py", line 10, in <module>
    from .builtin_frames import ITRS
  File "/home/yfeng1/.local/lib/python2.7/site-packages/astropy/coordinates/builtin_frames/__init__.py", line 28, in <module>
    from .fk5 import FK5
  File "/home/yfeng1/.local/lib/python2.7/site-packages/astropy/coordinates/builtin_frames/fk5.py", line 12, in <module>
    from .utils import EQUINOX_J2000
  File "/home/yfeng1/.local/lib/python2.7/site-packages/astropy/coordinates/builtin_frames/utils.py", line 16, in <module>
    from ...utils import iers
  File "/home/yfeng1/.local/lib/python2.7/site-packages/astropy/utils/iers/__init__.py", line 4, in <module>
    from .iers import *
  File "/home/yfeng1/.local/lib/python2.7/site-packages/astropy/utils/iers/iers.py", line 62, in <module>
    from ...table import Table
  File "/home/yfeng1/.local/lib/python2.7/site-packages/astropy/table/__init__.py", line 25, in <module>
    from .jsviewer import JSViewer
  File "/home/yfeng1/.local/lib/python2.7/site-packages/astropy/table/jsviewer.py", line 190, in <module>
    io_registry.register_writer('jsviewer', Table, write_table_jsviewer)
  File "/home/yfeng1/.local/lib/python2.7/site-packages/astropy/io/registry.py", line 189, in register_writer
    _update__doc__(data_class, 'write')
  File "/home/yfeng1/.local/lib/python2.7/site-packages/astropy/io/registry.py", line 105, in _update__doc__
    format_table = get_formats(data_class)
  File "/home/yfeng1/.local/lib/python2.7/site-packages/astropy/io/registry.py", line 68, in get_formats
    format_table.sort(['Data class', 'Deprecated', 'Format'])
  File "/home/yfeng1/.local/lib/python2.7/site-packages/astropy/table/table.py", line 1851, in sort
    indexes = self.argsort(keys)
  File "/home/yfeng1/.local/lib/python2.7/site-packages/astropy/table/table.py", line 1813, in argsort
    return data.argsort(**kwargs)
  File "/home/yfeng1/.local/lib/python2.7/site-packages/numpy/core/_internal.py", line 307, in _parse_order
    name, flag = name
ValueError: too many values to unpack

```

**Comment by njmiller** [comment]
It looks like the error happens due to this statement in the code "from astropy.coordinates import SkyCoord" which would be some sort of issue with astropy. Do you get the error if you just try to run that import statement? What versions of astropy and numpy do you have?

**Comment by rainwoodman** [comment]
Seems to be so. I am using the development version of numpy.

**Comment by rainwoodman** [comment]
Indeed. After downgrading to 1.10.1 the examples worked smooth as butter.
