### ISSUE TITLE
Broken with matplotlib>=3.5.0

### ISSUE THREAD

**Issue by msyriac** [nasa-lambda/cmb_footprint#5]
This package has stopped working with versions of matplotlib>=3.5.0 and cbar=True. Here is the output for one of the examples:

```
$ python plot_lss.py 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
WARNING: AstropyDeprecationWarning: "verbose" was deprecated in version 1.15.0 and will be removed in a future version.  [cmb_footprint.config_handler]
WARNING: AstropyDeprecationWarning: "verbose" was deprecated in version 1.15.0 and will be removed in a future version.  [healpy.visufunc]
WARNING: AstropyDeprecationWarning: "verbose" was deprecated in version 1.15.0 and will be removed in a future version.  [cmb_footprint.config_handler]
Traceback (most recent call last):
  File "/home/msyriac/repos/cmb_footprint/examples/plot_lss.py", line 28, in <module>
    fp.superimpose_survey('BOSS-LSS-RANDOM2',color='green')
  File "/home/msyriac/repos/cmb_footprint/footprint.py", line 323, in superimpose_survey
    self.superimpose_hpxmap(hpx_map, label, color=color,
  File "/home/msyriac/repos/cmb_footprint/footprint.py", line 168, in superimpose_hpxmap
    self.fig.colorbar(im0, cax=ax_color, orientation='horizontal',
  File "/home/msyriac/.local/lib/python3.10/site-packages/matplotlib/figure.py", line 1158, in colorbar
    cb = cbar.Colorbar(cax, mappable, **cb_kw)
  File "/home/msyriac/.local/lib/python3.10/site-packages/matplotlib/colorbar.py", line 493, in __init__
    self.draw_all()
  File "/home/msyriac/.local/lib/python3.10/site-packages/matplotlib/colorbar.py", line 577, in draw_all
    X, Y, extendlen = self._mesh()
  File "/home/msyriac/.local/lib/python3.10/site-packages/matplotlib/colorbar.py", line 1132, in _mesh
    y, extendlen = self._proportional_y()
  File "/home/msyriac/.local/lib/python3.10/site-packages/matplotlib/colorbar.py", line 1247, in _proportional_y
    y = np.ma.filled(norm(y), np.nan)
  File "/home/msyriac/.local/lib/python3.10/site-packages/matplotlib/colors.py", line 1245, in __call__
    raise ValueError("minvalue must be less than or equal to maxvalue")
ValueError: minvalue must be less than or equal to maxvalue
```

**Comment by njmiller** [comment]
Thanks. I will look into it.

**Comment by njmiller** [comment]
I believe I fixed the issue, though the colorbars will show the variable transparency now instead of just the solid color used for the footprint.
